<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260322071016 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Initial migration';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE log (id UUID NOT NULL, name VARCHAR(100) NOT NULL, object_id UUID NOT NULL, level VARCHAR(20) NOT NULL, text TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, context JSONB NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE preset (id UUID NOT NULL, title VARCHAR(255) NOT NULL, width INT NOT NULL, height INT NOT NULL, codec VARCHAR(50) NOT NULL, bitrate DOUBLE PRECISION NOT NULL, log JSONB DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE tariff (id UUID NOT NULL, title VARCHAR(255) NOT NULL, delay INT NOT NULL, instance INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE task (id UUID NOT NULL, status INT NOT NULL, progress INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, meta JSON NOT NULL, deleted BOOLEAN DEFAULT FALSE NOT NULL, video_id UUID NOT NULL, preset_id UUID NOT NULL, user_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_527EDB2529C1004E ON task (video_id)');
        $this->addSql('CREATE INDEX IDX_527EDB2580688E6F ON task (preset_id)');
        $this->addSql('CREATE INDEX IDX_527EDB25A76ED395 ON task (user_id)');
        $this->addSql('CREATE INDEX idx_task_deleted ON task (deleted)');
        $this->addSql('CREATE TABLE "user" (id UUID NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) DEFAULT NULL, tariff_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8D93D64992348FD2 ON "user" (tariff_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE video (id UUID NOT NULL, title VARCHAR(255) NOT NULL, extension VARCHAR(10) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, meta JSONB NOT NULL, deleted BOOLEAN DEFAULT FALSE NOT NULL, user_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7CC7DA2CA76ED395 ON video (user_id)');
        $this->addSql('CREATE INDEX idx_video_deleted ON video (deleted)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB2529C1004E FOREIGN KEY (video_id) REFERENCES video (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB2580688E6F FOREIGN KEY (preset_id) REFERENCES preset (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB25A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D64992348FD2 FOREIGN KEY (tariff_id) REFERENCES tariff (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE video ADD CONSTRAINT FK_7CC7DA2CA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');

        $this->addSql('INSERT INTO "user" (id, email, roles, password) VALUES (\'123e4567-e89b-42d3-a456-426614174000\', \'oleg@milantiev.com\', \'["ROLE_ADMIN"]\', \'$2y$13$aMbt0.agYrHEOjmVLRu0tOa94hWeIErYcW6JPUo0EOFX2PoCzus5m\')');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE task DROP CONSTRAINT FK_527EDB2529C1004E');
        $this->addSql('ALTER TABLE task DROP CONSTRAINT FK_527EDB2580688E6F');
        $this->addSql('ALTER TABLE task DROP CONSTRAINT FK_527EDB25A76ED395');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D64992348FD2');
        $this->addSql('ALTER TABLE video DROP CONSTRAINT FK_7CC7DA2CA76ED395');
        $this->addSql('DROP TABLE log');
        $this->addSql('DROP TABLE preset');
        $this->addSql('DROP TABLE tariff');
        $this->addSql('DROP TABLE task');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE video');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
