<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260307124315 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create preset, task and video tables';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE preset (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, width INT NOT NULL DEFAULT 0, height INT NOT NULL DEFAULT 0, codec VARCHAR(50) NOT NULL, bitrate INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE task (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(50) NOT NULL, progress INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, video_id UUID NOT NULL, preset_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_527EDB2529C1004E ON task (video_id)');
        $this->addSql('CREATE INDEX IDX_527EDB2580688E6F ON task (preset_id)');
        $this->addSql('COMMENT ON COLUMN task.video_id IS \'(DC2Type:uuid)\'');
        $this->addSql('CREATE TABLE video (id UUID NOT NULL, extension VARCHAR(10) NOT NULL, title VARCHAR(255) NOT NULL, status VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7CC7DA2CA76ED395 ON video (user_id)');
        $this->addSql('COMMENT ON COLUMN video.id IS \'(DC2Type:uuid)\'');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB2529C1004E FOREIGN KEY (video_id) REFERENCES video (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB2580688E6F FOREIGN KEY (preset_id) REFERENCES preset (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE video ADD CONSTRAINT FK_7CC7DA2CA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE task DROP CONSTRAINT FK_527EDB2529C1004E');
        $this->addSql('ALTER TABLE task DROP CONSTRAINT FK_527EDB2580688E6F');
        $this->addSql('ALTER TABLE video DROP CONSTRAINT FK_7CC7DA2CA76ED395');
        $this->addSql('DROP TABLE preset');
        $this->addSql('DROP TABLE task');
        $this->addSql('DROP TABLE video');
    }
}
