<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260420201249 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Init';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE log (id UUID NOT NULL, name VARCHAR(100) NOT NULL, action VARCHAR(100) NOT NULL, object_id UUID DEFAULT NULL, level VARCHAR(20) NOT NULL, text TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, context JSONB NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_log_name ON log (name)');
        $this->addSql('CREATE INDEX idx_log_object_id ON log (object_id)');
        $this->addSql('CREATE INDEX idx_log_level ON log (level)');
        $this->addSql('CREATE INDEX idx_log_text ON log (text)');
        $this->addSql('CREATE INDEX idx_log_created_at ON log (created_at)');
        $this->addSql('CREATE TABLE preset (id UUID NOT NULL, title VARCHAR(255) NOT NULL, video_codec VARCHAR(50) NOT NULL, audio_codec VARCHAR(50) NOT NULL, format VARCHAR(10) NOT NULL, bitrate JSONB DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE tariff (id UUID NOT NULL, title VARCHAR(255) NOT NULL, delay INT NOT NULL, instance INT NOT NULL, video_duration INT NOT NULL, video_size DOUBLE PRECISION NOT NULL, max_width INT NOT NULL, max_height INT NOT NULL, storage_gb DOUBLE PRECISION NOT NULL, storage_hour INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE tariff_preset (tariff_entity_id UUID NOT NULL, preset_entity_id UUID NOT NULL, PRIMARY KEY (tariff_entity_id, preset_entity_id))');
        $this->addSql('CREATE INDEX IDX_3C8F39A2CE73AC3B ON tariff_preset (tariff_entity_id)');
        $this->addSql('CREATE INDEX IDX_3C8F39A2437EEC20 ON tariff_preset (preset_entity_id)');
        $this->addSql('CREATE TABLE task (id UUID NOT NULL, status INT NOT NULL, progress INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, meta JSON NOT NULL, deleted BOOLEAN DEFAULT false NOT NULL, video_id UUID NOT NULL, preset_id UUID NOT NULL, user_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_527EDB2580688E6F ON task (preset_id)');
        $this->addSql('CREATE INDEX idx_task_video_id ON task (video_id)');
        $this->addSql('CREATE INDEX idx_task_user_active ON task (user_id) WHERE (deleted = false)');
        $this->addSql('CREATE TABLE "user" (id UUID NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, logined_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, tariff_id UUID DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8D93D64992348FD2 ON "user" (tariff_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE video (id UUID NOT NULL, title VARCHAR(255) NOT NULL, extension VARCHAR(10) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, meta JSONB NOT NULL, deleted BOOLEAN DEFAULT false NOT NULL, user_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7CC7DA2CA76ED395 ON video (user_id)');
        $this->addSql('CREATE INDEX idx_video_user_active ON video (user_id) WHERE (deleted = false)');
        $this->addSql('ALTER TABLE tariff_preset ADD CONSTRAINT FK_3C8F39A2CE73AC3B FOREIGN KEY (tariff_entity_id) REFERENCES tariff (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tariff_preset ADD CONSTRAINT FK_3C8F39A2437EEC20 FOREIGN KEY (preset_entity_id) REFERENCES preset (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB2529C1004E FOREIGN KEY (video_id) REFERENCES video (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB2580688E6F FOREIGN KEY (preset_id) REFERENCES preset (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB25A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D64992348FD2 FOREIGN KEY (tariff_id) REFERENCES tariff (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE video ADD CONSTRAINT FK_7CC7DA2CA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');

        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');

        $this->addSql("INSERT INTO public.preset (id, video_codec, audio_codec, format, title, bitrate) VALUES ('8646d1a5-3f87-4382-8abe-7341e18ed0f0', 'h264', 'aac', 'mp4', 'Standard video Quality', '{\"144\": 0.2, \"240\": 0.4, \"360\": 1, \"480\": 2.5, \"720\": 5, \"1080\": 8, \"1440\": 16, \"2160\": 35, \"4320\": 85}')");
        $this->addSql("INSERT INTO public.preset (id, video_codec, audio_codec, format, title, bitrate) VALUES ('13390296-44de-48f2-afcf-05af02006a9d', 'h265', 'aac', 'mp4', 'High video Quality', '{\"144\": 0.06, \"240\": 0.25, \"360\": 0.6, \"480\": 1.5, \"720\": 3, \"1080\": 5, \"1440\": 10, \"2160\": 20, \"4320\": 50}')");
        $this->addSql("INSERT INTO public.preset (id, video_codec, audio_codec, format, title, bitrate) VALUES ('889a2546-a2bc-44d5-bc03-231f307ae3d7', 'h265', 'opus', 'mp4', 'High video Quality, High Efficiency Audio', '{\"144\": 0.06, \"240\": 0.25, \"360\": 0.6, \"480\": 1.5, \"720\": 3, \"1080\": 5, \"1440\": 10, \"2160\": 20, \"4320\": 50}')");
        $this->addSql("INSERT INTO public.preset (id, video_codec, audio_codec, format, title, bitrate) VALUES ('d136829d-c1af-4fca-b670-7236e64fdced', 'vp9', 'opus', 'webm', 'High video Quality+, High Efficiency Audio', '{\"144\": 0.06, \"240\": 0.25, \"360\": 0.6, \"480\": 1.5, \"720\": 3, \"1080\": 5, \"1440\": 10, \"2160\": 20, \"4320\": 50}')");
        $this->addSql("INSERT INTO public.preset (id, video_codec, audio_codec, format, title, bitrate) VALUES ('ec070af7-ab40-440c-af9c-760b320025f4', 'av1', 'opus', 'webm', 'Ultra video Quality, High Efficiency Audio', '{\"144\": 0.04, \"240\": 0.15, \"360\": 0.4, \"480\": 1.0, \"720\": 2, \"1080\": 3.5, \"1440\": 7, \"2160\": 15, \"4320\": 35}')");
        $this->addSql("INSERT INTO public.preset (id, video_codec, audio_codec, format, title, bitrate) VALUES ('3ecc3746-530e-46c9-9755-573a552f3990', 'av1', 'opus', 'mp4', 'Ultra video Quality, High Efficiency Audio', '{\"144\": 0.04, \"240\": 0.15, \"360\": 0.4, \"480\": 1.0, \"720\": 2, \"1080\": 3.5, \"1440\": 7, \"2160\": 15, \"4320\": 35}')");

        $this->addSql("INSERT INTO public.tariff (id, title, delay, instance, video_duration, video_size, max_width, max_height, storage_gb, storage_hour) VALUES ('21ce3067-53c0-4400-8921-8d3b22c9bd30', 'Premium', 0, 2, 3600, 100, 3840, 2160, 1, 24)");
        $this->addSql("INSERT INTO public.tariff (id, title, delay, instance, video_duration, video_size, max_width, max_height, storage_gb, storage_hour) VALUES ('905048e3-fd0f-408d-bffd-a596e896a92c', 'Free', 3600, 1, 3600, 100, 1920, 1280, 1, 24)");

        $this->addSql("INSERT INTO public.tariff_preset (tariff_entity_id, preset_entity_id) VALUES ('905048e3-fd0f-408d-bffd-a596e896a92c', '8646d1a5-3f87-4382-8abe-7341e18ed0f0')");
        $this->addSql("INSERT INTO public.tariff_preset (tariff_entity_id, preset_entity_id) VALUES ('21ce3067-53c0-4400-8921-8d3b22c9bd30', '8646d1a5-3f87-4382-8abe-7341e18ed0f0')");
        $this->addSql("INSERT INTO public.tariff_preset (tariff_entity_id, preset_entity_id) VALUES ('21ce3067-53c0-4400-8921-8d3b22c9bd30', 'ec070af7-ab40-440c-af9c-760b320025f4')");
        $this->addSql("INSERT INTO public.tariff_preset (tariff_entity_id, preset_entity_id) VALUES ('21ce3067-53c0-4400-8921-8d3b22c9bd30', '3ecc3746-530e-46c9-9755-573a552f3990')");
        $this->addSql("INSERT INTO public.tariff_preset (tariff_entity_id, preset_entity_id) VALUES ('21ce3067-53c0-4400-8921-8d3b22c9bd30', '889a2546-a2bc-44d5-bc03-231f307ae3d7')");
        $this->addSql("INSERT INTO public.tariff_preset (tariff_entity_id, preset_entity_id) VALUES ('21ce3067-53c0-4400-8921-8d3b22c9bd30', '13390296-44de-48f2-afcf-05af02006a9d')");
        $this->addSql("INSERT INTO public.tariff_preset (tariff_entity_id, preset_entity_id) VALUES ('21ce3067-53c0-4400-8921-8d3b22c9bd30', 'd136829d-c1af-4fca-b670-7236e64fdced')");

         // Admin user: oleg@milantiev.com / admin
         $this->addSql('INSERT INTO "user" (id, email, roles, password, created_at, tariff_id) VALUES (\'123e4567-e89b-42d3-a456-426614174000\', \'oleg@milantiev.com\', \'["ROLE_ADMIN", "ROLE_USER"]\', \'$2y$13$aMbt0.agYrHEOjmVLRu0tOa94hWeIErYcW6JPUo0EOFX2PoCzus5m\', NOW(), \'21ce3067-53c0-4400-8921-8d3b22c9bd30\')');
         // Test user: test@test.com / test
         $this->addSql('INSERT INTO "user" (id, email, roles, password, created_at, tariff_id) VALUES (\'0c4178c4-d8ea-4915-a1ee-757b06482318\', \'test@test.com\', \'["ROLE_USER"]\', \'$2y$13$5MPQQimDKdiKH4heuhvXF.riOmhsm.eyPcmbzcKb8L72i0K.SKrCW\', NOW(), \'905048e3-fd0f-408d-bffd-a596e896a92c\')');

         $this->addSql('CREATE EXTENSION IF NOT EXISTS pg_stat_statements');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP EXTENSION IF EXISTS pg_stat_statements');
        $this->addSql('ALTER TABLE tariff_preset DROP CONSTRAINT FK_3C8F39A2CE73AC3B');
        $this->addSql('ALTER TABLE tariff_preset DROP CONSTRAINT FK_3C8F39A2437EEC20');
        $this->addSql('ALTER TABLE task DROP CONSTRAINT FK_527EDB2529C1004E');
        $this->addSql('ALTER TABLE task DROP CONSTRAINT FK_527EDB2580688E6F');
        $this->addSql('ALTER TABLE task DROP CONSTRAINT FK_527EDB25A76ED395');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D64992348FD2');
        $this->addSql('ALTER TABLE video DROP CONSTRAINT FK_7CC7DA2CA76ED395');
        $this->addSql('DROP TABLE log');
        $this->addSql('DROP TABLE preset');
        $this->addSql('DROP TABLE tariff');
        $this->addSql('DROP TABLE tariff_preset');
        $this->addSql('DROP INDEX IF EXISTS idx_task_user_active');
        $this->addSql('DROP TABLE task');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP INDEX IF EXISTS idx_video_user_active');
        $this->addSql('DROP TABLE video');
    }
}
