# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    videos_directory: '%kernel.project_dir%/public/uploads'
    videos_public_path: '/uploads'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Interface binding
    App\Domain\Video\Service\Storage\StorageInterface: '@App\Infrastructure\Storage\FilesystemStorage'
    App\Domain\Repository\VideoRepositoryInterface: '@App\Repository\VideoRepository'
    App\Infrastructure\Ffmpeg\ProcessRunnerInterface: '@App\Infrastructure\Ffmpeg\SymfonyProcessRunner'
    App\Application\Service\Mercure\MercurePublisherInterface: '@App\Infrastructure\Mercure\HttpMercurePublisher'
    App\Application\Logging\LogServiceInterface:
        class: App\Infrastructure\Logging\CompositeLogService
        arguments:
            $loggers: !tagged_iterator app.logger

    # arguments
    App\Infrastructure\Storage\FilesystemStorage:
        arguments:
            $storagePath: '%kernel.project_dir%/public/uploads'
            $publicPath: '/uploads'

    TusPhp\Cache\RedisStore:
        class: TusPhp\Cache\RedisStore
        arguments:
            $options:
                host: "%env(REDIS_HOST)%"
                port: "%env(int:REDIS_PORT)%"
                scheme: 'tcp'

    TusPhp\Tus\Server:
        class: TusPhp\Tus\Server
        arguments:
            $cacheAdapter: '@TusPhp\Cache\RedisStore'
        calls:
            - method: setUploadDir
              arguments:
                  - '%kernel.project_dir%/var/cache/uploads'
            - method: setApiPath
              arguments:
                  - '/api/upload'

    # tags
    monolog.processor.uid:
        class: Monolog\Processor\UidProcessor
        tags: ['monolog.processor']

    monolog.processor.web:
        class: Monolog\Processor\WebProcessor
        tags: ['monolog.processor']

    monolog.processor.memory_usage:
        class: Monolog\Processor\MemoryUsageProcessor
        tags: ['monolog.processor']

    App\Infrastructure\Logging\PromtailLogService:
        tags: ['app.logger']

    App\Infrastructure\Logging\DoctrineLogService:
        tags: ['app.logger']

    App\Infrastructure\Logging\TelegramLogService:
        tags: ['app.logger']

