services:
    nginx:
        restart: always
        image: olegmilantiev/yc-nginx:${PROJECT_VERSION}
        expose:
            - 80
            - 443
        depends_on:
            - php

    php:
        restart: always
        image: olegmilantiev/yc-php:${PROJECT_VERSION}
        env_file:
            - .env
        depends_on:
            redis:
                condition: service_started
            postgres:
                condition: service_healthy
        expose:
            - 9000
        volumes:
            # TODO а как в prod обычно file-кеши чистят? У каждого ящика?
            - symfony-var:/var/www/yc/var

    ffmpeg:
        restart: always
        image: olegmilantiev/yc-ffmpeg:${PROJECT_VERSION}
        env_file:
            - .env
        depends_on:
            redis:
                condition: service_started
            postgres:
                condition: service_healthy
        command: sh -c '/var/www/yc/bin/console messenger:consume async -vvv'
        mem_limit: 256m
        deploy:
            replicas: 1
            resources:
                limits:
                    memory: 256M
        volumes:
            - symfony-var:/var/www/yc/var

    ffmpeg-transcode:
        restart: always
        image: olegmilantiev/yc-ffmpeg:${PROJECT_VERSION}
        env_file:
            - .env
        depends_on:
            redis:
                condition: service_started
            postgres:
                condition: service_healthy
        command: sh -c '/var/www/yc/bin/console messenger:consume async_transcode -vvv'
        mem_limit: 256m
        deploy:
            replicas: 2
            resources:
                limits:
                    memory: 256M
        volumes:
            - symfony-var:/var/www/yc/var

    redis:
        restart: always
        image: redis:7
        expose:
            - 6379

    postgres:
        restart: always
        image: docker.io/postgres:16.2
        shm_size: 1g
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
            interval: 5s
            timeout: 5s
            retries: 5
        expose:
            - 5432
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        volumes:
            - ./postgresql:/host
            - db-data:/var/lib/postgresql/data

    playwright:
        image: mcr.microsoft.com/playwright:v1.53.0-jammy
        depends_on:
            - nginx
        working_dir: /work/e2e
        command: ["bash", "-lc", "sleep infinity"]
        volumes:
            - ./e2e:/work/e2e
            - ./release.check:/work/release.check

volumes:
    # PostgreSQL data volume
    db-data:

    symfony-var:

networks:
    appnet:
        driver: bridge
