framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_ASYNC_DSN)%'
                options:
                    consumer: '%env(HOSTNAME)%'
                    group: async
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            async_transcode:
                dsn: '%env(MESSENGER_TRANSPORT_ASYNC_TRANSCODE_DSN)%'
                options:
                    consumer: '%env(HOSTNAME)%'
                    group: async_transcode
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        default_bus: messenger.bus.command

        buses:
            messenger.bus.command:
                default_middleware:
                    enabled: true
                    allow_no_handlers: false
                    allow_no_senders: true
            messenger.bus.event:
                default_middleware:
                    enabled: true
                    allow_no_handlers: true
                    allow_no_senders: true

        routing:
            App\Application\Command\Task\TranscodeVideo: async_transcode

            App\Application\Command\Video\ExtractVideoMetadata: async
            App\Application\Command\Video\CreateVideoPreview: async
            App\Application\Command\Video\CleanupDeletedVideoMedia: async

            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async
